# Procesamiento inicial
serie de valores de demanda diaria consumo de energia Alemania
se cargan los datos de los ultimos 10 años y se calcula el promedio por semana, se calcula periodograma

In [9]:
# librerías
import numpy as np
import pandas as pd
import datetime

# visual
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns
import plotly.graph_objects as go
plt.style.use("seaborn-v0_8-darkgrid")
sns.set_palette("viridis")
import time

In [10]:
# serie original 
date_close =  pd.read_csv("./csv/EC_GER.csv", delimiter=";")
date_close

,Start date,End date,grid load [MWh] Calculated resolutions,Grid load incl. hydro pumped storage [MWh] Calculated resolutions,Hydro pumped storage [MWh] Calculated resolutions,Residual load [MWh] Calculated resolutions
0,"Jan 1, 2015","Jan 2, 2015","1,096,852.75","1,122,748.25","25,895.50","768,472.25"
1,"Jan 2, 2015","Jan 3, 2015","1,288,914.75","1,316,139.75","27,225.00","679,205.75"
2,"Jan 3, 2015","Jan 4, 2015","1,213,309.50","1,238,003.75","24,694.25","736,911.75"
3,"Jan 4, 2015","Jan 5, 2015","1,177,896.00","1,202,337.75","24,441.75","767,345.50"
4,"Jan 5, 2015","Jan 6, 2015","1,425,927.50","1,451,660.75","25,733.25","1,172,036.25"
...,...,...,...,...,...,...
4014,"Dec 28, 2025","Dec 29, 2025","1,164,857.13","1,182,122.92","17,265.80","790,740.23"
4015,"Dec 29, 2025","Dec 30, 2025","1,271,758.77","1,290,002.13","18,243.36","629,522.68"
4016,"Dec 30, 2025","Dec 31, 2025","1,240,018.15","1,265,047.56","25,029.42","634,889.03"
4017,"Dec 31, 2025","Jan 1, 2026","1,222,968.93","1,244,085.10","21,116.17","415,316.66"
4018,"Jan 1, 2026","Jan 2, 2026","1,175,901.84","1,226,080.15","50,178.31","41,311.13"

In [11]:
date_close =  pd.read_csv("./csv/EC_GER.csv", delimiter=";")
# se escogen solo las columnas requeridas
date_close = date_close[["Start date", "grid load [MWh] Calculated resolutions"]]
date_close["Start date"] = pd.to_datetime(date_close["Start date"])
date_close = date_close.rename(columns={"grid load [MWh] Calculated resolutions": "value"})
date_close["value"] = date_close["value"].str.replace(",", "", regex=False).astype(float)
date_close.head()

  Start date       value
0 2015-01-01  1096852.75
1 2015-01-02  1288914.75
2 2015-01-03  1213309.50
3 2015-01-04  1177896.00
4 2015-01-05  1425927.50

In [15]:
df_date_close = date_close.set_index("Start date")
df_date_close.index = pd.to_datetime(df_date_close.index)
df_weekly = df_date_close.resample('W-MON').mean()
#df_weekly = df_date_close.resample('W-MON').sum()
#df_weekly = df_weekly.reset_index()
df_weekly

                   value
Start date
2015-01-05  1.240580e+06
2015-01-12  1.465239e+06
2015-01-19  1.479857e+06
2015-01-26  1.516270e+06
2015-02-02  1.507588e+06
...                  ...
2025-12-08  1.445384e+06
2025-12-15  1.410001e+06
2025-12-22  1.338978e+06
2025-12-29  1.206173e+06
2026-01-05  1.212963e+06

[575 rows x 1 columns]

se exporta el df agrupado semanal a un csv

In [16]:
# weekly_sum = df_date_close.resample("W-MON").sum()
# weekly_count = df_date_close.resample("W-MON").count()
# 
# df_weekly_clean = weekly_sum[weekly_count["value"] == 7]
# df_weekly_clean

In [17]:

df_weekly.to_csv("./csv/EC_GER_Weekly.csv")
# df_weekly_clean.to_csv("./csv/EC_GER_Weekly.csv")